In [1]:
# Import numpy library
import numpy as np

In [2]:
# Single Dimensional Array
# np.array():- array() of numpy library is used to create array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Two dimensional array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
# ndim:- ndim is a property of numpy which is used to find the dimension of array
print(a.ndim)

2


In [5]:
# itemsize:- itemsize is a property of numpy which is used to find required
# memory for one element.
print(a.itemsize)

4


In [6]:
# dtype:- dtype is a property of numpy which is used to find datatype of 
# element.
print(a.dtype)

int32


In [7]:
# size:- size is a property of numpy which is used to find how many elements 
# in array.
# shape:- shape is property of numpy which is used to find no. of rows and 
# columns in array
print("Size of array=",a.size)
print("Shape of array=",a.shape)

Size of array= 6
Shape of array= (2, 3)


In [8]:
# reshape():- The reshape function of numpy is used to change the shape of array.
a=np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [9]:
print(a.shape)

(2, 3)


In [10]:
a=a.reshape(3,2)
print(a)

[[1 2]
 [3 3]
 [4 5]]


In [11]:
print(a.shape)

(3, 2)


In [14]:
# linspace():- linspace() function of numpy is used to generate evenly spaced 
# numbers in given range.
a=np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [16]:
print(a.dtype)
print(a.size)

float64
20


In [17]:
# Use of max(), min() and sum() functions
a=np.array([1,2,5])
print(a)

[1 2 5]


In [18]:
print(a.max())

5


In [19]:
print(a.min())

1


In [20]:
print(a.sum())

8


In [21]:
# np.mean():- This function is used to find the mean of array.
print(np.mean(a))

2.6666666666666665


In [22]:
# np.sqrt():- This function is used to find square root of each element of array.
# np.std():- This function is used to find standard deviation.
print(a)

[1 2 5]


In [23]:
print(np.sqrt(a))

[1.         1.41421356 2.23606798]


In [24]:
print("Standard Deviation=",np.std(a))

Standard Deviation= 1.699673171197595


In [25]:
# zeros():- zeros() function of numpy is used to create array of zeros.
a=np.zeros((2,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# identity():- indentity() function of numpy is used to create identity matrix.
ide=np.identity(5)
print(ide)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
# Use of arange()
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]
